DROP TABLE IF EXISTS TRANSACTIONS;

CREATE TABLE TRANSACTIONS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  transactionType VARCHAR(250) NOT NULL,
  userId VARCHAR(250) NOT NULL,
  amount VARCHAR(250) NOT NULL,
  transactionDate VARCHAR(250) NOT NULL
);